-- ==========================================================
-- INVENTORY ENGINE SCHEMA & ATOMIC OPERATIONS
-- Member 2 Backend Contribution
-- ==========================================================

-- 1. TABLES
DROP TABLE IF EXISTS stock_levels CASCADE;
DROP TABLE IF EXISTS stock_ledger CASCADE;

CREATE TABLE stock_levels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id TEXT NOT NULL,
    location_id TEXT NOT NULL,
    quantity NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (quantity >= 0),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (product_id, location_id)
);

CREATE TABLE stock_ledger (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMPTZ DEFAULT NOW(),
    action_type TEXT NOT NULL,
    product_id TEXT NOT NULL,
    source_location TEXT,
    destination_location TEXT,
    quantity_change NUMERIC(12, 2) NOT NULL,
    balance_after NUMERIC(12, 2),
    reference_id TEXT
);

ALTER TABLE stock_levels DISABLE ROW LEVEL SECURITY;
ALTER TABLE stock_ledger DISABLE ROW LEVEL SECURITY;

-- 2. STEP 1: VALIDATE RECEIPT
CREATE OR REPLACE FUNCTION validate_receipt(
    p_receipt_id TEXT,
    p_product_id TEXT,
    p_location_id TEXT,
    p_received_qty NUMERIC
)
RETURNS JSONB
LANGUAGE plpgsql
AS $$
DECLARE
    v_new_balance NUMERIC;
BEGIN
    IF p_received_qty <= 0 THEN
        RAISE EXCEPTION 'Received quantity must be greater than zero.';
    END IF;

    INSERT INTO stock_levels (product_id, location_id, quantity, updated_at)
    VALUES (p_product_id, p_location_id, p_received_qty, NOW())
    ON CONFLICT (product_id, location_id)
    DO UPDATE SET 
        quantity = stock_levels.quantity + EXCLUDED.quantity,
        updated_at = NOW()
    RETURNING quantity INTO v_new_balance;

    INSERT INTO stock_ledger (action_type, product_id, destination_location, quantity_change, balance_after, reference_id)
    VALUES ('RECEIPT', p_product_id, p_location_id, p_received_qty, v_new_balance, p_receipt_id);

    RETURN jsonb_build_object('status', 'SUCCESS', 'new_balance', v_new_balance);
END;
$$;

-- 3. STEP 2: VALIDATE DELIVERY ORDER (BLOCKS INSUFFICIENT STOCK)
CREATE OR REPLACE FUNCTION validate_delivery_order(
    p_order_id TEXT,
    p_product_id TEXT,
    p_location_id TEXT,
    p_delivered_qty NUMERIC
)
RETURNS JSONB
LANGUAGE plpgsql
AS $$
DECLARE
    v_current_stock NUMERIC;
    v_new_balance NUMERIC;
BEGIN
    IF p_delivered_qty <= 0 THEN
        RAISE EXCEPTION 'Delivered quantity must be greater than zero.';
    END IF;

    SELECT quantity INTO v_current_stock
    FROM stock_levels
    WHERE product_id = p_product_id AND location_id = p_location_id
    FOR UPDATE;

    IF v_current_stock IS NULL OR v_current_stock < p_delivered_qty THEN
        RAISE EXCEPTION 'Insufficient stock. Available: %, Requested: %', COALESCE(v_current_stock, 0), p_delivered_qty;
    END IF;

    v_new_balance := v_current_stock - p_delivered_qty;

    UPDATE stock_levels
    SET quantity = v_new_balance, updated_at = NOW()
    WHERE product_id = p_product_id AND location_id = p_location_id;

    INSERT INTO stock_ledger (action_type, product_id, source_location, quantity_change, balance_after, reference_id)
    VALUES ('DELIVERY', p_product_id, p_location_id, -p_delivered_qty, v_new_balance, p_order_id);

    RETURN jsonb_build_object('status', 'SUCCESS', 'new_balance', v_new_balance);
END;
$$;

-- 4. STEP 3: INTERNAL TRANSFERS & ADJUSTMENTS
CREATE OR REPLACE FUNCTION execute_internal_transfer(
    p_transfer_id TEXT,
    p_product_id TEXT,
    p_src_location TEXT,
    p_dest_location TEXT,
    p_qty NUMERIC
)
RETURNS JSONB
LANGUAGE plpgsql
AS $$
DECLARE
    v_src_balance NUMERIC;
BEGIN
    IF p_qty <= 0 THEN
        RAISE EXCEPTION 'Transfer quantity must be greater than zero.';
    END IF;

    SELECT quantity INTO v_src_balance
    FROM stock_levels
    WHERE product_id = p_product_id AND location_id = p_src_location
    FOR UPDATE;

    IF v_src_balance IS NULL OR v_src_balance < p_qty THEN
        RAISE EXCEPTION 'Insufficient stock at source location.';
    END IF;

    UPDATE stock_levels 
    SET quantity = quantity - p_qty, updated_at = NOW()
    WHERE product_id = p_product_id AND location_id = p_src_location;

    INSERT INTO stock_levels (product_id, location_id, quantity, updated_at)
    VALUES (p_product_id, p_dest_location, p_qty, NOW())
    ON CONFLICT (product_id, location_id)
    DO UPDATE SET quantity = stock_levels.quantity + EXCLUDED.quantity, updated_at = NOW();

    INSERT INTO stock_ledger (action_type, product_id, source_location, destination_location, quantity_change, reference_id)
    VALUES ('TRANSFER', p_product_id, p_src_location, p_dest_location, p_qty, p_transfer_id);

    RETURN jsonb_build_object('status', 'SUCCESS');
END;
$$;

CREATE OR REPLACE FUNCTION execute_stock_adjustment(
    p_adjustment_id TEXT,
    p_product_id TEXT,
    p_location_id TEXT,
    p_counted_qty NUMERIC
)
RETURNS JSONB
LANGUAGE plpgsql
AS $$
DECLARE
    v_current_qty NUMERIC;
    v_diff NUMERIC;
BEGIN
    IF p_counted_qty < 0 THEN
        RAISE EXCEPTION 'Counted quantity cannot be negative.';
    END IF;

    SELECT COALESCE(quantity, 0) INTO v_current_qty
    FROM stock_levels
    WHERE product_id = p_product_id AND location_id = p_location_id
    FOR UPDATE;

    v_diff := p_counted_qty - v_current_qty;

    INSERT INTO stock_levels (product_id, location_id, quantity, updated_at)
    VALUES (p_product_id, p_location_id, p_counted_qty, NOW())
    ON CONFLICT (product_id, location_id)
    DO UPDATE SET quantity = EXCLUDED.quantity, updated_at = NOW();

    INSERT INTO stock_ledger (action_type, product_id, destination_location, quantity_change, balance_after, reference_id)
    VALUES ('ADJUSTMENT', p_product_id, p_location_id, v_diff, p_counted_qty, p_adjustment_id);

    RETURN jsonb_build_object('status', 'SUCCESS', 'diff', v_diff, 'new_stock', p_counted_qty);
END;
$$;